
#pragma config(Sensor, S1,     ColorLeft,      sensorNone)
#pragma config(Sensor, S2,     Gyro,           sensorNone)
#pragma config(Sensor, S3,     ColorRight,     sensorNone)
#pragma config(Sensor, S4,     UltraSonic,     sensorNone)
#pragma config(Motor,  motorA,          MotorCenter,   tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          MotorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//stop Machine for 1 second
void stop_Machine(){
	setMotorSpeed(MotorLeft, 0);
	setMotorSpeed(MotorRight, 0);
	sleep(1000);
}

void removingObject(){
	//short myev3 = legoev3;
	//beep(myev3,1);
	playSound(soundBeepBeep);
	//grab the object
	setMotorTarget(MotorCenter,-90,20);
	stop_Machine();
	//get degree of Gyro Sensor
	float degree = getGyroDegrees(Gyro);
	//If degree is bigger than -90 turn left;
	while(degree < 90){
		setMotorSpeed(MotorRight,-10);
		setMotorSpeed(MotorLeft,10);
		degree = getGyroDegrees(Gyro);
	}
	stop_Machine();

	//raise the arm
	setMotorTarget(MotorCenter,90,20);
	sleep(1000);

	//go back for 0.5 second
	setMotorSpeed(MotorLeft, -15);
	setMotorSpeed(MotorRight, -15);
	sleep(250);

	//return the machine to the same postion
	while(degree > 0){
		setMotorSpeed(MotorLeft,-10);
		setMotorSpeed(MotorRight,10);
		degree = getGyroDegrees(Gyro);
	}
	stop_Machine();
	resetGyro(Gyro);
}

task main()
{
	setMotorBrakeMode(MotorLeft, motorCoast);
	setMotorBrakeMode(MotorRight, motorCoast);
	resetMotorEncoder(MotorLeft);
	resetMotorEncoder(MotorCenter);
	resetMotorEncoder(MotorRight);
	//distance checked by Ultra Sonic Sensor
	float Ultra_dis = 0;
	//set the degree of the Gyro Sensor to 0
	resetGyro(Gyro);
	while(true)
	{
		//check the distance
		Ultra_dis = getUSDistance(UltraSonic);
		//if Ultra_dis is less than or equal to 4, remove the object to the side
		if(Ultra_dis <= 6){
			removingObject();
		}
		else{
			resetGyro(Gyro);
			float degree = getGyroDegrees(Gyro);
			int RightColour = getColorReflected(ColorRight);
			int RightColourName = getColorName(ColorRight);
			//if it see green line, turn 180 degree
			if(RightColourName == 3){

				while(RightColour  != 5){
					setMotorSpeed(MotorRight,10);
					setMotorSpeed(MotorLeft,-10);
					degree = getGyroDegrees(Gyro);
					RightColour = getColorReflected(ColorRight);				}
			}
			//black line tracking
			if(RightColour < 20){
				setMotorSpeed(MotorLeft, 20);
				setMotorSpeed(MotorRight, 20);
			}
			else{
				while(degree > -30 && RightColour > 20){
					setMotorSpeed(MotorRight,10);
					setMotorSpeed(MotorLeft,-10);
					degree = getGyroDegrees(Gyro);
					RightColour = getColorReflected(ColorRight);
				}
				while(degree < 30 && RightColour > 20){
					setMotorSpeed(MotorRight,-10);
					setMotorSpeed(MotorLeft,10);
					degree = getGyroDegrees(Gyro);
					RightColour = getColorReflected(ColorRight);
				}
			}
		}
	}
}
