#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	//go straight until scan a black bar
	while (getColorReflected(colorSensor) > 10) {
		displayCenteredBigTextLine(2, "ColorValue %d", getColorReflected(colorSensor));
		setMotorSpeed(rightMotor, 25);
		setMotorSpeed(leftMotor, 25);
	}

	//stop at the beginning of the barcode
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 0);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	//flush data on file
	displayCenteredBigTextLine(2, "BARCODE READ");
	datalogFlush();
	datalogClose();
	datalogClear();
	
	bool datalogOpen = datalogOpen(0, 1, false);
	if (!datalogOpen) {
		displayCenteredBigTextLine(6, "Cannot open datalog.");
	}

	//scanning and data logging
	//move to the end of the barcode
	// 2 wheel rotations for the length of the barcode paper
	// 720 encoder value
	while (getMotorEncoder(leftMotor) < 720) {
		setMotorSpeed(leftMotor, 5);
		setMotorSpeed(rightMotor, 5);

		datalogDataGroupStart();
		datalogAddValue(1, getColorReflected(colorSensor));
		sleep(300);
		datalogDataGroupEnd();

	}
	//close file
	datalogClose();
}