#pragma config(Sensor, S1,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     UltraSonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// set screen height and width
const int screenHeight = 127;
const int screenWidth  = 177;

// Set numbers of row and column for the maze
const int numOfRows = 4;
const int numOfCols = 6;

// variable for the direction robot is facing
int robHeading = 0; // 0=North, 1=East, 2=South, 3=West

// struct for 1 cell of the maze
typedef struct{
	int nWall;  // 0 = door, 1 = wall
	int eWall;
	int sWall;
	int wWall;
}cell;

// create a 4x6 maze
cell maze[numOfRows][numOfCols];

// Set Starting position
int startRow = 0;
int startcol = 0;
int robRow = startRow;
int robCol = startcol;

// Set target point
int targetRow = 1;
int targetCol = 3;

// Declare an array to record navigation
int navigationArray[99];
int index = 0;

// Functions prototype
void buildOuterBorders();
void gridDraw();
void drawBot();
void turnRight();
void turnLeft();
void goFwd();
void MazeSolver();
int turn180(int head);
int checkTurningDegree(int position);

void refreshScreen();
void MazeSim();
void mazeSolverRHF();
void pathFinder();

task main(){

	// Create the maze on the EV3 screen
	buildOuterBorders();
	MazeSim();

	// Calling function: Solving the maze with right hand side algorithm
	mazeSolverRHF();
	
	// Flash "maze solved" on the screen
	for(int i=0;i< 2;i++){
		eraseDisplay();
		sleep(500);
		displayCenteredTextLine(3,"Maze Solved !!");
		sleep(500);
	}
	
	// Make sound when maze is solved
	playSound(soundBeepBeep);
	
	// Stop the robot
	resetGyro(Gyro);
	setMotorSpeed(Left,0);
	setMotorSpeed(Right,0);
	sleep(500);
	
	// Turn 90 degree
	while(getGyroDegrees(Gyro) != 90){
		if(getGyroDegrees(Gyro) < 90){
			setMotorSpeed(Left,10);
			setMotorSpeed(Right,-10);
		}
		if(getGyroDegrees(Gyro) > 90){
			setMotorSpeed(Left,-10);
			setMotorSpeed(Right,10);
		}
	}
	
	// stop again
	setMotorSpeed(Left,0);
	setMotorSpeed(Right,0);
	sleep(500);
	
	// Call function to go back with shortest path
	pathFinder();
}

// Function to solve maze with righ-hand wall strategy (on EV3 screen)
void mazeSolverRHF(){

	turnRight();

	while((robCol != targetCol) || (robRow != targetRow) ){

		switch(robHeading){
		case 0: //North
			if(maze[robRow][robCol].nWall == 1){
				turnLeft();
				continue;
			}
			navigationArray[index] = 0;
			break;
		case 1:  // facing east
			if(maze[robRow][robCol].eWall == 1){
				turnLeft();
				continue;
			}
			navigationArray[index] = 1;
			break;
		case 2: // South
			if(maze[robRow][robCol].sWall == 1){
				turnLeft();
				continue;
			}
			navigationArray[index] = 2;
			break;
		case 3: //West
			if(maze[robRow][robCol].wWall == 1){
				turnLeft();
				continue;
			}
			navigationArray[index] = 3;
			break;
		default: break;
		}
		goFwd();
		turnRight();
		MazeSolver();
		index++;
		sleep(500);
	}

}

// Function to Navigate in physical world
void MazeSolver(){
	
	// Ram into the wall to adjust robot's position
	float frontWall = getUSDistance(UltraSonic);
	if(frontWall < 10){
		setMotorSpeed(Left,10);
		setMotorSpeed(Right,10);
		sleep(2000);
		setMotorSpeed(Left,-10);
		setMotorSpeed(Right,-10);
		sleep(100);
	}
	
	// Turn 90 degree
	resetGyro(Gyro);
	sleep(500);
	while(getGyroDegrees(Gyro) != 90){
		if(getGyroDegrees(Gyro) < 90){
			setMotorSpeed(Left,10);
			setMotorSpeed(Right,-10);
		}
		if(getGyroDegrees(Gyro) > 90){
			setMotorSpeed(Left,-10);
			setMotorSpeed(Right,10);
		}
	}
	// Stop
	setMotorSpeed(Left,0);
	setMotorSpeed(Right,0);
	sleep(500);
	
	// Check for right wall, if no wall, go straigth one cell
	float rightWall = getUSDistance(UltraSonic);
	if(rightWall > 20){
		resetMotorEncoder(Left);
		while(getMotorEncoder(Left) < 450){
			setMotorSpeed(Left,20);
			setMotorSpeed(Right,20);
		}
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
	}

	// Else if nothing in front, go straigth one cell
	else if(frontWall > 20){
		// Minor correction due to gyro error - Turn left back to 0 position
		while(getGyroDegrees(Gyro) != 5){
			if(getGyroDegrees(Gyro) < 5){
				setMotorSpeed(Left,10);
				setMotorSpeed(Right,-10);
			}
			if(getGyroDegrees(Gyro) > 5){
				setMotorSpeed(Left,-10);
				setMotorSpeed(Right,10);
			}
		}
		// Stop
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
		// Go straigth one cell in case no wall
		resetMotorEncoder(Left);
		while(getMotorEncoder(Left) < 450){
			setMotorSpeed(Left,20);
			setMotorSpeed(Right,20);
		}
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
	}
	
	// Else Turn left
	else{
		while(getGyroDegrees(Gyro) != 5){
			if(getGyroDegrees(Gyro) < 5){
				setMotorSpeed(Left,10);
				setMotorSpeed(Right,-10);
			}
			if(getGyroDegrees(Gyro) > 5){
				setMotorSpeed(Left,-10);
				setMotorSpeed(Right,10);
			}
		}
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
		while(getGyroDegrees(Gyro) != -85){
			if(getGyroDegrees(Gyro) < -85){
				setMotorSpeed(Left,10);
				setMotorSpeed(Right,-10);
			}
			if(getGyroDegrees(Gyro) > -85){
				setMotorSpeed(Left,-10);
				setMotorSpeed(Right,10);
			}
		}
		// Check for wall again, if no wall, go straigth 1 cell
		int leftWall = getUSDistance(UltraSonic);
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
		if(leftWall > 20){
			resetMotorEncoder(Left);
			while(getMotorEncoder(Left) < 450){
				setMotorSpeed(Left,20);
				setMotorSpeed(Right,20);
			}
			setMotorSpeed(Left,0);
			setMotorSpeed(Right,0);
			sleep(500);
		}
		else{
			while(getGyroDegrees(Gyro) != -175){
				if(getGyroDegrees(Gyro) < -178){
					setMotorSpeed(Left,10);
					setMotorSpeed(Right,-10);
				}
				if(getGyroDegrees(Gyro) > -175){
					setMotorSpeed(Left,-10);
					setMotorSpeed(Right,10);
				}
			}
			setMotorSpeed(Left,0);
			setMotorSpeed(Right,0);
			sleep(500);
			resetMotorEncoder(Left);
			while(getMotorEncoder(Left) < 450){
				setMotorSpeed(Left,20);
				setMotorSpeed(Right,20);
			}
			setMotorSpeed(Left,0);
			setMotorSpeed(Right,0);
			sleep(500);
		}
	}
}


// Function to go back with shortest path
void pathFinder(){
	// Reduce the navigation array to the shortest path
	for(int i=0;i<index-1;i++){
		if((navigationArray[i] - navigationArray[i+1] == 2) || (navigationArray[i] - navigationArray[i+1] == -2)){
			for(int j = i; j < index-2;j++){
				navigationArray[j] = navigationArray[(j+2)];
			}
			index-=2;
			i = -1;
		}
	}

	//loop through array from last element to the first.
	for(int i=index-1;i>=0;i--){
		//turning degree of robot is the direction it will head - the current direction * 90 because it is  in degree.
		int turningDegree = (checkTurningDegree(turn180(navigationArray[i])));
		robHeading = turn180(navigationArray[i]);
		goFwd();
		sleep(500);

		//ram into wall everytime the robot sense the wall in the front to adjust the position.
		float frontWall = getUSDistance(UltraSonic);
		if(frontWall < 10){
			setMotorSpeed(Left,10);
			setMotorSpeed(Right,10);
			sleep(2000);
			setMotorSpeed(Left,-10);
			setMotorSpeed(Right,-10);
			sleep(500);
		}
		//stop for 0.5 second
		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		sleep(500);
		//reset gyro sensor and the motor encoder
		//turn to the desired position
		for(int i=0;i< turningDegree;i++){
			resetGyro(Gyro);
			setMotorSpeed(Left,0);
			setMotorSpeed(Right,0);
			sleep(500);
			while(getGyroDegrees(Gyro) != 90){
				if(getGyroDegrees(Gyro) < 90){
					setMotorSpeed(Left,10);
					setMotorSpeed(Right,-10);
				}
				if(getGyroDegrees(Gyro) > 90){
					setMotorSpeed(Left,-10);
					setMotorSpeed(Right,10);
				}
			}
		}

		setMotorSpeed(Left,0);
		setMotorSpeed(Right,0);
		resetMotorEncoder(Left);
		sleep(500);
		//move forward for one block
		while(getMotorEncoder(Left) < 300){
			setMotorSpeed(Left,20);
			setMotorSpeed(Right,20);
		}

	}
}

// Function to draw Maze
void MazeSim(){

	maze[0][1].eWall = maze[0][2].wWall = 1;
	maze[0][2].eWall = maze[0][3].wWall = 1;
	maze[0][3].nWall = maze[1][3].sWall = 1;
	maze[0][4].eWall = maze[0][5].wWall = 1;

	maze[1][0].eWall = maze[1][1].wWall = 1;
	maze[1][1].nWall = maze[2][1].sWall = 1;
	maze[1][1].eWall = maze[1][2].wWall = 1;
	maze[1][3].nWall = maze[2][3].sWall = 1;
	maze[1][4].eWall = maze[1][5].wWall = 1;

	maze[2][1].nWall = maze[3][1].sWall = 1;
	maze[2][2].eWall = maze[2][3].wWall = 1;
	maze[2][3].eWall = maze[2][4].wWall = 1;
	maze[2][5].nWall = maze[3][5].sWall = 1;

	maze[3][1].eWall = maze[3][2].wWall = 1;
	maze[3][3].eWall = maze[3][4].wWall = 1;
}


// Refresh screen
void refreshScreen(){
	eraseDisplay();
	gridDraw();
	drawBot();
}

// Robot go foward on screen
void goFwd(){
	refreshScreen();
	wait1Msec(250);  // waste some time to simulate motion

	if (robHeading==0) {   // Going Fwd North
		robRow++;
	}
	else if (robHeading==1) {   // Going Fwd East
		robCol++;
	}
	else if (robHeading==2) {   // Going Fwd South
		robRow--;
	}
	else if (robHeading==3) {   // Going Fwd West
		robCol--;
	}
	else {
		robRow = 99;
		robCol = 99;
	}

}

// Turn right on screen
void turnRight(){
	refreshScreen();
	if (robHeading < 3){
		robHeading++;
	}
	else robHeading=0;
}

//Turn left on screen
void turnLeft(){
	refreshScreen();
	if (robHeading > 0){
		robHeading--;
	}
	else robHeading=3;
}

// Flip the value to the opposite direction
int turn180(int head){
	if(head == 0){
		return 2;
	}
	if(head == 1){
		return 3;
	}
	if(head == 2){
		return 0;
	}
	if(head == 3){
		return 1;
	}
	else return 99;
}
// Calculate number of 90-degree turns
int checkTurningDegree(int position){
	int NumOfTurning=0;
	while(robHeading != position){
		NumOfTurning ++;
		if (robHeading < 3){
			robHeading++;
		}
		else robHeading=0;
	}
	return NumOfTurning;
}

// Draw maze borders
void buildOuterBorders(){
	for(int col=0; col<numOfCols; col++){
		maze[0][col].sWall = 1;
		maze[numOfRows-1][col].nWall = 1;
	}

	for(int row=0; row<numOfRows; row++){
		maze[row][0].wWall = 1;
		maze[row][numOfCols-1].eWall = 1;
	}
}



//=====================================================================
void gridDraw(){
	int XStart=0;
	int YStart=0;
	int XEnd  =0;
	int YEnd  =0;
	for(int i=0;i<numOfRows;i++){
		for(int j=0;j<numOfCols;j++){
			if(maze[i][j].nWall==1){
				XStart= j   *screenWidth/numOfCols;
				YStart=(i+1)*screenHeight/numOfRows;
				XEnd  =(j+1)*screenWidth/numOfCols;
				YEnd  =(i+1)*screenHeight/numOfRows;
				drawLine(XStart,YStart,XEnd,YEnd);
			}
			if (maze[i][j].eWall==1){
				XStart=(j+1)*screenWidth/numOfCols;
				YStart=(i)*screenHeight/numOfRows;
				XEnd  =(j+1)*screenWidth/numOfCols;
				YEnd  =(i+1)*screenHeight/numOfRows;
				drawLine(XStart,YStart,XEnd,YEnd);
			}
			if (maze[i][j].wWall==1){
				XStart= j   *screenWidth/numOfCols;
				YStart=(i)*screenHeight/numOfRows;
				XEnd  =(j)*screenWidth/numOfCols;
				YEnd  =(i+1)*screenHeight/numOfRows;
				drawLine(XStart,YStart,XEnd,YEnd);
			}
			if(maze[i][j].sWall==1){
				XStart= j   *screenWidth/numOfCols;
				YStart=(i)*screenHeight/numOfRows;
				XEnd  =(j+1)*screenWidth/numOfCols;
				YEnd  =(i)*screenHeight/numOfRows;
				drawLine(XStart,YStart,XEnd,YEnd);
			}
		}
	}
}

//=====================================================================
void drawBot(){
	int RobotXpixelPos=0;
	int RobotYpixelPos=0;

	if(robCol==0){
		RobotXpixelPos=screenWidth/12;
	}
	else{
		RobotXpixelPos=(2*robCol+1)*screenWidth/12;
	}

	if(robRow==0){
		RobotYpixelPos=screenHeight/8;
	}
	else{
		RobotYpixelPos=(2*robRow+1)*screenHeight/8;
	}

	switch(robHeading){
	case 0: displayStringAt(RobotXpixelPos,RobotYpixelPos,"^"); break; // Facing North
	case 1: displayStringAt(RobotXpixelPos,RobotYpixelPos,">"); break; // Facing East
	case 2: displayStringAt(RobotXpixelPos,RobotYpixelPos,"V"); break; // Facing South
	case 3: displayStringAt(RobotXpixelPos,RobotYpixelPos,"<"); break; // Facing West
	default: break;
	}
}
